spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
  h2:
    console:
      enabled: true
  profiles:
    active: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/ossp
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

server:
  port: 8084

file:
  dir: "/Users/kimjungwon/pictureStore/"